const INDEX_TYPE_MAP: Record<string, "EXPOSURE" | "SENSITIVITY" | "ADAPTIVE" | "NONE"> = {
  "gender": "NONE",
  "heat-information-sources": "NONE",
  "risk-factors": "EXPOSURE",
  "medical-care": "EXPOSURE",
  "work-types": "EXPOSURE",
  "itsi-identification": "SENSITIVITY",
  "postcode": "SENSITIVITY",
  "age-group": "SENSITIVITY",
  "dependents": "SENSITIVITY",
  "english-comprehension": "SENSITIVITY",
  "general-health": "SENSITIVITY",
  "long-term-conditions": "SENSITIVITY",
  "heat-sensitive-medicines": "SENSITIVITY",
  "pregnant-breastfeeding": "SENSITIVITY",
  "daily-assistance": "SENSITIVITY",
  "household-situation": "SENSITIVITY",
  "social-support": "SENSITIVITY",
  "social-support-person": "SENSITIVITY",
  "cooling-method": "ADAPTIVE",
  "cooling-effectiveness": "ADAPTIVE",
  "cooling-affordability": "ADAPTIVE",
  "home-built-year": "ADAPTIVE",
  "home-type": "ADAPTIVE",
  "wall-material": "ADAPTIVE",
  "roof-type": "ADAPTIVE",
  "home-insulation": "ADAPTIVE",
  "external-shading": "ADAPTIVE",
  "home-modification": "ADAPTIVE",
  "routine-flexibility": "ADAPTIVE",
  "work-study-flexibility": "ADAPTIVE",
  "cool-retreat-knowledge": "ADAPTIVE",
  "local-amenities": "ADAPTIVE",
  "heatwave-transport": "ADAPTIVE",
  "data-connectivity": "ADAPTIVE",
};
export default INDEX_TYPE_MAP;